name: Pipeline Check

on:
  push:
    branches-ignore:
      - "*"

jobs:
  check_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check for changes in package.json
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only $(curl -s "${{ github.event.compare }}" | jq -r '.base_commit.sha')...HEAD | grep -E "package\.json$" || true)
          if [[ -n "$CHANGED_FILES" ]]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Trigger pipeline check
        if: ${{ steps.check_changes.outputs.changed == 'true' }}
        run: |
          # Perform actions to trigger pipeline check, e.g., API call or running a script
          echo "Pipeline check triggered"
