name: Check Package.json Changes

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  check_package_json_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        run: |
          echo "::set-output name=changed_files::$(git rev-parse --short HEAD)"

      - name: Check for package.json changes
        id: package_json_changes
        run: |
          CHANGED_FILES="${{ steps.changed_files.outputs.changed_files }}"
          if [[ "$CHANGED_FILES" =~ "package.json" ]]; then
            echo "::set-output name=package_json_changed::true"
          else
            echo "::set-output name=package_json_changed::false"
          fi

      - name: Comment on pull request
        if: steps.package_json_changes.outputs.package_json_changed == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const prNumber = context.issue.number;
            const commentBody = 'Warning: The `package.json` file has changed in this pull request.';

            github.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: prNumber,
              body: commentBody
            });
